version: "3.9"

services:
  app:
    build: .
    container_name: rekapin_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: rekapin_redis
    ports:
      - "6379:6379"
    restart: always

  worker:
    build: .
    container_name: rekapin_worker
    command: ["python", "worker.py"]
    env_file: .env
    depends_on:
      - redis
    restart: always
